### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by GoCool2k19**

### CODE REVIEW

**Comment by GoCool2k19** [comment]
LGTM

**Review by GoCool2k19 — COMMENTED** [review]
Approved

**Review by GoCool2k19 — COMMENTED** [review]
LGTM

**Comment by GoCool2k19** [comment]
Approved

**Comment by Tronde** [comment]
Hi,
you've set absolute paths and values for several variables. While this may fit for you and your use case it may not for others. That's why I use placeholders in the first place. Therefore I don't merge and close this request.

Thanks,  
Tronde

**Pull request closed without merging**
